services:
  db:
    image: postgres:latest
    container_name: "booking-db"
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  grpc:
    ports:
      - "50051:50051"
    build: .
    depends_on:
      - db
volumes:
  pgdata: